name: twig
description: "Mobile app frontend for the Perch V2 bioacoustic classification model."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.0
  permission_handler: ^12.0.1
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.2
  http: ^1.1.0
  url_launcher: ^6.2.2
  fftea: ^1.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - weights/model_float16.tflite
    - weights/assets/labels.csv
    - weights/assets/enhanced_labels.csv
    - weights/assets/perch_v2_ebird_classes.csv
    - LICENSE

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#549342"